In [1]:
import uproot
import pyarrow.parquet as pq
import pandas as pd
import pyarrow as pa

In [2]:
HWp = \
uproot.open("/Users/shoh/Projects/CMS/PhD/Analysis/SSL/dataset-v12-VH/TTJets_SingleLeptFromTbar_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_ext1-v1.root")["Events"]

In [3]:
mainscheme=[
    'nElectron',
 #'Electron_deltaEtaSC',
 #'Electron_dr03EcalRecHitSumEt',
 #'Electron_dr03HcalDepth1TowerSumEt',
 #'Electron_dr03TkSumPt',
 'Electron_dxy',
 'Electron_dxyErr',
 'Electron_dxyErr_ugo',
 'Electron_dxy_ugo',
 'Electron_dz',
 'Electron_dzErr',
 #'Electron_eCorr',
 #'Electron_eInvMinusPInv',
 #'Electron_energyErr',
 'Electron_eta',
 #'Electron_hoe',
 #'Electron_ip3d',
 #'Electron_ip3d_ugo',
 'Electron_mass',
 'Electron_miniPFRelIso_all',
 'Electron_miniPFRelIso_chg',
 'Electron_mvaSpring16GP',
 'Electron_mvaSpring16HZZ',
 'Electron_pfRelIso03_all',
 'Electron_pfRelIso03_chg',
 'Electron_phi',
 'Electron_pt',
 #'Electron_r9',
 #'Electron_sieie',
 #'Electron_sip3d',
 #'Electron_sip3d_ugo',
 #'Electron_mvaTTH',
 'Electron_charge',
 'Electron_jetIdx',
 'Electron_pdgId',
 'Electron_photonIdx',
 'Electron_tightCharge',
 #'Electron_vidNestedWPBitmap',
 #'Electron_lostHits',
 'nGenJetAK8',
 'GenJetAK8_eta',
 'GenJetAK8_mass',
 'GenJetAK8_phi',
 'GenJetAK8_pt',
 'nGenJet',
 'GenJet_eta',
 'GenJet_mass',
 'GenJet_phi',
 'GenJet_pt',
 'nGenPart',
 'GenPart_eta',
 'GenPart_mass',
 'GenPart_phi',
 'GenPart_pt',
 'GenPart_genPartIdxMother',
 'GenPart_pdgId',
 'GenPart_status',
 'GenPart_statusFlags',
 'nJet',
 'Jet_area',
 'Jet_btagCMVA',
 'Jet_btagCSVV2',
 'Jet_btagDeepB',
 'Jet_btagDeepC',
 'Jet_chEmEF',
 'Jet_chHEF',
 'Jet_eta',
 'Jet_mass',
 'Jet_neEmEF',
 'Jet_neHEF',
 'Jet_phi',
 'Jet_pt',
 'Jet_qgl',
 #'Jet_rawFactor',
 'Jet_bReg',
 'Jet_electronIdx1',
 'Jet_electronIdx2',
 'Jet_jetId',
 'Jet_muonIdx1',
 'Jet_muonIdx2',
 'Jet_nConstituents',
 'Jet_nElectrons',
 'Jet_nMuons',
 'Jet_puId',
 #'MET_MetUnclustEnUpDeltaX',
 #'MET_MetUnclustEnUpDeltaY',
 #'MET_covXX',
 #'MET_covXY',
 #'MET_covYY',
 'MET_phi',
 'MET_pt',
 #'MET_significance',
 'MET_sumEt',
 'nMuon',
 'Muon_dxy',
 #'Muon_dxyErr',
 #'Muon_dxyErr_ugo',
 #'Muon_dxy_ugo',
 #'Muon_dz',
 #'Muon_dzErr',
 'Muon_eta',
 'Muon_ip3d',
 'Muon_ip3d_ugo',
 'Muon_mass',
 'Muon_miniPFRelIso_all',
 'Muon_miniPFRelIso_chg',
 'Muon_pfRelIso03_all',
 'Muon_pfRelIso03_chg',
 'Muon_pfRelIso04_all',
 'Muon_phi',
 'Muon_pt',
 'Muon_ptErr',
 #'Muon_segmentComp',
 #'Muon_sip3d',
 #'Muon_sip3d_ugo',
 #'Muon_mvaTTH',
 'Muon_charge',
 'Muon_jetIdx',
 #'Muon_nStations',
 #'Muon_nTrackerLayers',
 'Muon_pdgId',
 'Muon_tightCharge',
 'Muon_highPtId',
 'Pileup_nPU',
 'Pileup_nTrueInt',
 'PuppiMET_phi',
 'PuppiMET_pt',
 'PuppiMET_sumEt',
 'PV_ndof',
 'PV_x',
 'PV_y',
 'PV_z',
 'PV_chi2',
 'PV_score',
 'PV_npvs',
 'Electron_genPartIdx',
 'Electron_genPartFlav',
 'GenJetAK8_partonFlavour',
 'GenJetAK8_hadronFlavour',
 'GenJet_partonFlavour',
 'GenJet_hadronFlavour',
 'Jet_genJetIdx',
 'Jet_hadronFlavour',
 'Jet_partonFlavour',
 'Muon_genPartIdx',
 'Muon_genPartFlav',
 #'MET_fiducialGenPhi',
 #'MET_fiducialGenPt',
 #'Electron_cleanmask',
 #'Jet_cleanmask',
 #'Muon_cleanmask',
       ]

globalboolscheme= [
 'HLT_Ele25_WPTight_Gsf',
 'HLT_Ele27_eta2p1_WPLoose_Gsf',
 'HLT_Ele105_CaloIdVT_GsfTrkIdT',
 'HLT_IsoMu22',
 'HLT_IsoMu22_eta2p1',
 'HLT_IsoMu24',
 'HLT_IsoTkMu22_eta2p1',
 'HLT_IsoTkMu24',
 'HLT_Mu45_eta2p1',
 'HLT_Mu50',
# 'HLT_PFMET170_NoiseCleaned',
# 'HLT_PFMET170_JetIdCleaned',
# 'HLT_PFMET100_PFMHT100_IDTight',
# 'HLT_PFMET100_PFMHT100_IDTight_BeamHaloCleaned',
# 'HLT_PFMET110_PFMHT110_IDTight',
# 'HLT_PFMETNoMu90_PFMHTNoMu90_IDTight',
# 'HLT_PFMETNoMu100_PFMHTNoMu100_IDTight',
# 'HLT_PFMETNoMu110_PFMHTNoMu110_IDTight',
# 'HLT_PFMETNoMu120_PFMHTNoMu120_IDTight',
]
localboolscheme= [
 'Muon_mediumId',
 'Muon_softId',
 'Muon_tightId',
# 'Muon_isPFcand',
# 'Electron_convVeto',
# 'Electron_cutBased_HEEP',
# 'Electron_isPFcand',
# 'Electron_mvaSpring16GP_WP80',
# 'Electron_mvaSpring16GP_WP90',
# 'Electron_mvaSpring16HZZ_WPL',
 'Electron_cutBased',
# 'Electron_cutBased_HLTPreSel',
]

maintest=[
'GenJetAK8_eta',
 'GenJetAK8_mass',
 'GenJetAK8_phi',
 'GenJetAK8_pt',
 'nGenJet',
]

## Checking type from different scheme

In [ ]:
#for element in mainscheme:
#    if (HWp.arrays('%s' %element)['%s' %element]).dtype=="object":
#        if ((HWp.arrays('%s' %element)['%s' %element]).content).dtype=="bool":
#            print "BOOL FOUND in ", element
#        #else:
#            #print "element = ", element ," is clean with type = ", ((HWp.arrays('%s' %element)['%s' %element]).content).dtype
#    elif (HWp.arrays('%s' %element)['%s' %element]).dtype=="bool":
#        print "BOOL FOUND in ", element
#    #else:
#        #print "element = ", element ," is clean with type = ", (HWp.arrays('%s' %element)['%s' %element]).dtype
#

## Local Boolean Scheme conversion

In [4]:
import awkward
from array import array
import numpy as np

DFlb=[]
for element in localboolscheme:
    event=[]
    for jaggedElement in HWp.arrays("%s" %element)["%s" %element]:
        eventlet=[]
        for num,eve in enumerate(jaggedElement):
            eventlet.append(1*eve)
        event.append(eventlet)
        
    DFlb.append(pd.DataFrame(pd.Series([x for x in awkward.JaggedArray.fromiter(event)], name='%s' %element)))

In [5]:
DFlb[0]

        Muon_mediumId
0              [1, 1]
1              [1, 1]
2              [1, 1]
3              [1, 1]
4              [1, 1]
5              [1, 1]
6              [1, 1]
7              [1, 1]
8           [1, 1, 1]
9              [1, 1]
10             [1, 1]
11             [1, 1]
12             [1, 1]
13             [1, 1]
14             [1, 1]
15             [1, 1]
16             [1, 1]
17             [1, 1]
18             [1, 1]
19          [1, 1, 1]
20          [1, 1, 1]
21             [1, 0]
22             [1, 1]
23             [1, 1]
24       [1, 1, 1, 1]
25             [1, 1]
26             [1, 1]
27             [1, 1]
28             [1, 1]
29       [1, 1, 1, 1]
...               ...
1089167     [1, 1, 1]
1089168        [1, 1]
1089169        [1, 1]
1089170        [1, 1]
1089171        [1, 1]
1089172        [1, 1]
1089173        [1, 1]
1089174        [1, 1]
1089175        [1, 1]
1089176        [1, 1]
1089177        [1, 1]
1089178        [1, 1]
1089179        [1, 1]
1089180        [1, 1]
1089181        [1, 1]
1089182     [1, 1, 1]
1089183        [0, 1]
1089184        [1, 1]
1089185     [1, 1, 0]
1089186        [1, 0]
1089187        [1, 1]
1089188        [1, 1]
1089189        [1, 1]
1089190     [1, 0, 1]
1089191        [1, 1]
1089192        [1, 1]
1089193  [1, 0, 0, 0]
1089194     [1, 1, 1]
1089195        [1, 1]
1089196     [1, 1, 1]

[1089197 rows x 1 columns]

## Global Boolean Scheme Conversion

- Array as event entry

In [6]:
for element in globalboolscheme:
    DFlb.append(pd.DataFrame(pd.Series([1*x for x in HWp.arrays("%s" %element)["%s" %element]], name='%s' %element)))

In [8]:
DFlb[13]

         HLT_Mu50
0               1
1               0
2               0
3               1
4               1
5               0
6               0
7               1
8               0
9               0
10              0
11              1
12              0
13              1
14              1
15              1
16              0
17              0
18              0
19              0
20              0
21              1
22              0
23              1
24              1
25              1
26              0
27              1
28              1
29              1
...           ...
1089167         1
1089168         0
1089169         0
1089170         0
1089171         1
1089172         1
1089173         0
1089174         1
1089175         0
1089176         0
1089177         0
1089178         1
1089179         1
1089180         0
1089181         1
1089182         0
1089183         0
1089184         0
1089185         0
1089186         0
1089187         1
1089188         0
1089189         1
1089190         1
1089191         1
1089192         0
1089193         0
1089194         0
1089195         0
1089196         1

[1089197 rows x 1 columns]

## Main Scheme added

In [9]:
for element in maintest:
    DFlb.append(pd.DataFrame(pd.Series([x for x in HWp.arrays("%s" %element)["%s" %element]], name='%s' %element)))

In [10]:
DFlb[15]

                        GenJetAK8_mass
0                                   []
1                                   []
2                 [22.84375, 58.46875]
3                                   []
4                                   []
5                 [64.9375, 30.453125]
6                                   []
7                             [90.375]
8                                   []
9                                   []
10                                  []
11                          [40.03125]
12                           [76.5625]
13                                  []
14                           [54.4375]
15                          [4.109375]
16                                  []
17                                  []
18                                  []
19                                  []
20                  [95.4375, 27.0625]
21                           [89.6875]
22                  [43.5625, 46.9375]
23                                  []
24                                  []
25                                  []
26                                  []
27                              [52.0]
28                                  []
29                              [65.0]
...                                ...
1089167                             []
1089168                             []
1089169                             []
1089170                             []
1089171             [78.8125, 94.8125]
1089172                      [157.375]
1089173                             []
1089174                             []
1089175                             []
1089176                       [27.125]
1089177                             []
1089178              [84.75, 112.0625]
1089179                             []
1089180                             []
1089181                      [72.0625]
1089182                             []
1089183                             []
1089184                             []
1089185                             []
1089186                      [49.8125]
1089187                             []
1089188                             []
1089189  [106.1875, 60.40625, 93.3125]
1089190               [48.65625, 53.5]
1089191                      [71.3125]
1089192                             []
1089193                             []
1089194                             []
1089195                             []
1089196                             []

[1089197 rows x 1 columns]

In [13]:
TOTAL=pd.concat(DFlb, axis=1)

In [14]:
TOTAL

,Muon_mediumId,Muon_softId,Muon_tightId,Electron_cutBased,HLT_Ele25_WPTight_Gsf,HLT_Ele27_eta2p1_WPLoose_Gsf,HLT_Ele105_CaloIdVT_GsfTrkIdT,HLT_IsoMu22,HLT_IsoMu22_eta2p1,HLT_IsoMu24,HLT_IsoTkMu22_eta2p1,HLT_IsoTkMu24,HLT_Mu45_eta2p1,HLT_Mu50,GenJetAK8_eta,GenJetAK8_mass,GenJetAK8_phi,GenJetAK8_pt,nGenJet
0,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,1,1,[],[],[],[],6
1,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,0,0,[],[],[],[],5
2,"[1, 1]","[1, 1]","[1, 1]","[0, 0, 0]",0,0,0,1,1,1,1,1,0,0,"[-1.3679199, -0.8601074]","[22.84375, 58.46875]","[3.0922852, 0.6092529]","[197.63257, 184.4041]",7
3,"[1, 1]","[1, 1]","[1, 1]","[0, 0]",0,0,0,1,1,1,1,1,1,1,[],[],[],[],7
4,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,1,1,[],[],[],[],6
5,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,0,0,"[-0.6221924, -0.005604744]","[64.9375, 30.453125]","[-1.010498, 1.3371582]","[190.02478, 183.82887]",9
6,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,0,0,0,0,0,0,0,[],[],[],[],7
7,"[1, 1]","[1, 1]","[1, 1]","[0, 0]",0,0,0,1,1,1,1,1,1,1,[0.15890503],[90.375],[0.4664917],[275.4335],5
8,"[1, 1, 1]","[1, 1, 1]","[1, 1, 0]",[0],0,0,0,1,1,1,1,1,0,0,[],[],[],[],7
9,"[1, 1]","[1, 1]","[1, 1]","[0, 0]",0,0,0,1,1,1,1,1,0,0,[],[],[],[],9
10,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,0,0,[],[],[],[],6
11,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,1,1,[1.5205078],[40.03125],[-2.206543],[224.7548],6
12,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,1,0,[0.06997681],[76.5625],[0.5892334],[194.18307],10
13,"[1, 1]","[1, 1]","[1, 1]","[0, 0]",0,0,0,1,1,1,1,1,1,1,[],[],[],[],6
14,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,1,1,[0.07017517],[54.4375],[-0.032341003],[166.22359],8
15,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,1,1,[-0.99645996],[4.109375],[-1.2570801],[168.93703],6
16,"[1, 1]","[1, 1]","[1, 1]","[0, 0]",0,0,0,1,1,1,1,1,0,0,[],[],[],[],6
17,"[1, 1]","[1, 1]","[0, 1]",[0],0,0,0,0,0,0,0,0,0,0,[],[],[],[],8
18,"[1, 1]","[1, 1]","[1, 1]","[0, 0]",0,0,0,1,1,1,1,1,1,0,[],[],[],[],6
19,"[1, 1, 1]","[1, 1, 1]","[1, 1, 1]",[0],0,0,0,1,1,1,1,1,0,0,[],[],[],[],9
20,"[1, 1, 1]","[1, 1, 1]","[1, 1, 0]",[0],0,0,0,1,1,1,0,0,0,0,"[1.3015137, 2.1542969]","[95.4375, 27.0625]","[2.3237305, -0.16567993]","[178.02484, 161.35062]",10
21,"[1, 0]","[1, 0]","[1, 1]",[0],0,0,0,1,1,1,1,1,1,1,[0.18460083],[89.6875],[-1.2441406],[235.51491],13
22,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,0,0,"[-2.4179688, -0.6702881]","[43.5625, 46.9375]","[2.2016602, -0.7911377]","[184.21419, 169.4631]",9
23,"[1, 1]","[1, 1]","[1, 1]","[0, 0]",0,0,0,1,1,1,1,1,1,1,[],[],[],[],10
24,"[1, 1, 1, 1]","[1, 1, 1, 1]","[1, 1, 1, 1]",[0],0,0,0,1,1,1,1,1,1,1,[],[],[],[],11
25,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,1,1,[],[],[],[],7
26,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,0,0,0,0,0,0,0,[],[],[],[],9
27,"[1, 1]","[1, 1]","[1, 1]","[0, 0, 0]",0,0,0,1,1,1,1,1,1,1,[0.10978699],[52.0],[1.4204102],[225.73941],9
28,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,1,1,[],[],[],[],10
29,"[1, 1, 1, 1]","[1, 1, 1, 1]","[1, 1, 1, 1]",[0],0,0,0,1,1,1,1,1,1,1,[0.72314453],[65.0],[-2.5517578],[201.51671],11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1089167,"[1, 1, 1]","[1, 1, 0]","[1, 1, 0]",[0],0,0,0,1,1,1,1,1,1,1,[],[],[],[],6
1089168,"[1, 1]","[1, 1]","[1, 1]","[4, 0]",0,0,0,0,0,0,0,0,1,0,[],[],[],[],6
1089169,"[1, 1]","[1, 1]","[1, 1]","[0, 0]",0,0,0,1,0,1,0,1,0,0,[],[],[],[],10
1089170,"[1, 1]","[1, 1]","[1, 1]","[0, 0]",0,0,0,1,1,1,1,1,0,0,[],[],[],[],8
1089171,"[1, 1]","[1, 1]","[1, 1]","[0, 0]",0,0,0,0,0,0,0,0,1,1,"[-1.395752, -0.5788574]","[78.8125, 94.8125]","[1.0666504, -1.8493652]","[301.4856, 207.18102]",10
1089172,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,1,1,[-0.81591797],[157.375],[-2.727539],[374.10135],6
1089173,"[1, 1]","[1, 1]","[1, 1]","[0, 1]",0,0,0,1,1,1,1,1,0,0,[],[],[],[],6
1089174,"[1, 1]","[1, 1]","[1, 1]","[0, 0]",0,0,0,1,1,1,1,1,1,1,[],[],[],[],8
1089175,"[1, 1]","[1, 1]","[1, 1]","[0, 0, 0, 0]",0,0,0,1,1,1,1,1,0,0,[],[],[],[],8
1089176,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,0,0,[-0.77368164],[27.125],[-2.6591797],[177.09871],6
1089177,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,0,0,[],[],[],[],8
1089178,"[1, 1]","[1, 1]","[1, 1]","[0, 0]",0,0,0,1,1,1,1,1,1,1,"[0.9050293, -0.35095215]","[84.75, 112.0625]","[1.2019043, -1.6633301]","[283.51562, 184.30363]",10
1089179,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,1,1,[],[],[],[],9
1089180,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,1,0,[],[],[],[],8
1089181,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,1,1,[-2.0092773],[72.0625],[-2.4760742],[202.45258],7
1089182,"[1, 1, 1]","[1, 1, 1]","[1, 1, 1]","[0, 0, 0]",0,0,0,0,0,0,0,0,0,0,[],[],[],[],12
1089183,"[0, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,0,1,0,1,0,0,[],[],[],[],7
1089184,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,0,0,[],[],[],[],5
1089185,"[1, 1, 0]","[1, 1, 0]","[1, 1, 0]","[0, 0]",0,0,0,0,0,0,1,1,0,0,[],[],[],[],6
1089186,"[1, 0]","[1, 0]","[1, 0]","[0, 0]",0,0,0,1,1,1,1,1,0,0,[0.32104492],[49.8125],[-1.1174316],[165.23679],6
1089187,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,1,1,[],[],[],[],7
1089188,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,1,0,[],[],[],[],6
1089189,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,1,1,"[1.7714844, -0.58166504, 1.3630371]","[106.1875, 60.40625, 93.3125]","[2.503418, -1.2021484, 0.6561279]","[320.30783, 286.0595, 231.45702]",10
1089190,"[1, 0, 1]","[1, 1, 1]","[1, 1, 1]","[0, 0]",0,0,0,1,1,1,1,1,1,1,"[0.002389431, -0.119628906]","[48.65625, 53.5]","[-2.881836, 0.78674316]","[215.38531, 165.20784]",10
1089191,"[1, 1]","[1, 1]","[1, 1]","[0, 0]",0,0,0,1,1,1,1,1,1,1,[1.262207],[71.3125],[-0.9758301],[212.48592],14
1089192,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,0,0,[],[],[],[],6
1089193,"[1, 0, 0, 0]","[1, 0, 0, 0]","[1, 0, 0, 0]",[0],0,0,0,1,1,1,1,1,0,0,[],[],[],[],6
1089194,"[1, 1, 1]","[1, 1, 1]","[1, 1, 1]",[0],0,0,0,1,1,1,1,1,0,0,[],[],[],[],5
1089195,"[1, 1]","[1, 1]","[1, 1]",[0],0,0,0,1,1,1,1,1,0,0,[],[],[],[],6
1089196,"[1, 1, 1]","[1, 1, 1]","[1, 1, 1]",[0],0,0,0,1,1,1,1,1,1,1,[],[],[],[],9